### ISSUE TITLE
fix keyword processing (login breaks because of this)

### ISSUE THREAD

**Issue by jz359** [jz359/baeML#17]
namely:

1) make sure it processes and stores keywords from the article title, not content. it still processes content for some reason

2) add a length check before storing the keywords. e.g. if the length of the keyword is <4, don't put it in the user_keywords list.

**Comment by ef23** [comment]
fixed with:
https://github.com/jz359/baeML/commit/4210cecad0106ae49478272ed42486e1780fe324
https://github.com/jz359/baeML/commit/9d7721c36fa57503c67c800db27e567f029a170c
