### ISSUE TITLE
critical: fix SSLContext issue that is preventing login from working

### ISSUE THREAD

**Issue by jz359** [jz359/baeML#20]
it's apparently a problem with the webcrawler

do we need to add SSLContext for all the functions, not just grabContent()?
should/could we switch from using urllib2 to just using requests.get(url) to open links?

**Comment by ef23** [comment]
it works for me; requires python 2.7.13 though. also i broke python as a whole on my comp so ill probably do a reinstall in the near future LOL

ee283d22a3629a76c56b3b5f6d0f08fb84ce6178
