### ISSUE TITLE
handle opening session 

### ISSUE THREAD

**Issue by jc2729** [jz359/baeML#6]
-if not logged in, should show login page
-if logged in, gif shouldn't keep going
-gif keeps loading upon refreshing /feed

**Comment by ef23** [comment]
what do you mean 'loading upon refreshing', does that mean it loads for a bit then displays the feed or just continuously shows the gif

**Comment by jc2729** [comment]
Continuously shows the gif

**Comment by ef23** [comment]
when does it happen

**Comment by ef23** [comment]
this issue only happens on development server (when u save and it reloads meaning componentDidMount() never gets called), so it should never actually happen when deployed

**Comment by ef23** [comment]
no longer a problem with this 
https://github.com/jz359/baeML/commit/93166b773fd1541fdcc2887fe28298d4a42cfcfe
